version: '3.8'
services:
  backend:
    # Name of the service
    image: pahansith/chat-backend:v1
    ports:
      # Map TCP port 8000 inside the container to port 4000 on the Docker host
      - "5000:5000"
    restart: always
    # Ensures the container restarts if it exits or crashes

  frontend:
    image: pahansith/chat-ui:v1
    ports:
      # Map TCP port 3000 inside the container to port 3000 on the Docker host
      - "3000:3000"
    depends_on:
      # Ensures frontend starts only after the backend has started
      - backend
    restart: always
